---
- name: Configure Ubuntu 18.04 Server

# PROXY
# =====
#   * uncomment here everything related to proxy
#   * adjust file group_vars/all
  
  hosts: localhost
  connection: local


  roles:
#    - proxy_settings
    - logging
    - no_swap
    - bashrc_root
    - no_wifi
    - no_snap
    - apt_update
    - ansible
    - sshfs
    - docker
    - console_editors
    - console_file_managers
    - firewall_ufw
    
#  environment:
#    http_proxy: "{{proxy_env.http_proxy}}"
#    https_proxy: "{{proxy_env.https_proxy}}"
