---
- name: ensure perl is present
  become: yes
  apt:
    name: perl
    state: present
  tags:
    - citrix

- name: download citrix receiver page which contains the link
  become: yes
  get_url:
    url: https://www.citrix.com/downloads/citrix-receiver/linux/receiver-for-linux-latest.html
    dest: /tmp/receiver-for-linux-latest.html
    use_proxy: yes
  tags:
    - citrix

- name: getting the needed url to download the citrix client
  become: yes
  command: perl -ne 'if (m{<a .*rel="(//downloads.citrix.com/[0-9]+/icaclient_[0-9.]+_amd64.deb[^"]+)}) {print $1;};' /tmp/receiver-for-linux-latest.html
  register: citrix_url
  tags:
    - citrix

- name: download citrix
  become: yes
  get_url:
    url: "https:{{ citrix_url.stdout }}"
    dest: /tmp/ica.deb
  tags:
    - citrix

- name: install citrix
  become: yes
  apt:
    deb: /tmp/ica.deb
  tags:
    - citrix

- name: Add certificates for Citrix
  become: yes
  file:
    src: "{{ item.src }}"
    dest: "/opt/Citrix/ICAClient/keystore/cacerts/{{ item.path }}"
    state: link
    force: yes
  with_filetree: /usr/share/ca-certificates/mozilla/
  when: item.state=='file'
  loop_control:
    label: "{{ item.path }}"
  notify:
    - rehash certs
  tags:
    - citrix

- name: ensure plugin directories exist
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items:
    - /usr/lib/mozilla/plugins
    - /usr/lib/firefox-addons/plugins
  tags:
    - citrix

- name: Remove npwrapper libs
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/lib/mozilla/plugins/npwrapper.npica.so
    - /usr/lib/firefox/plugins/npwrapper.npica.so
  tags:
    - citrix

- name: Check, if mime-types already exist
  stat:
    path: "/home/{{ username }}/.config/mimeapps.list"
  register: mimeapps
  tags:
    - citrix

- name: Ensure, that citrix mime-type is in file
  lineinfile:
    path: "/home/{{ username }}/.config/mimeapps.list"
    line: 'application/x-ica=wfica.desktop'
    owner: "{{ username }}"
    group: "{{ username }}"
  when: mimeapps.stat.exists == true
  tags:
    - citrix

- name: chrome - citrix plugin
  shell: xdg-mime default wfica.desktop application/x-ica
  when: mimeapps.stat.exists == false
  tags:
    - citrix

