---
- name: ensure perl is present
  become: yes
  apt:
    name: perl
    state: present

- name: download citrix receiver page which contains the link
  become: yes
  get_url:
    url: https://www.citrix.com/downloads/citrix-receiver/linux/receiver-for-linux-latest.html
    dest: /tmp/receiver-for-linux-latest.html
    use_proxy: yes

- name: getting the needed url to download the citrix client
  become: yes
  command: perl -ne 'if (m{<a .*rel="(//downloads.citrix.com/[0-9]+/icaclient_[0-9.]+_amd64.deb[^"]+)}) {print $1;};' /tmp/receiver-for-linux-latest.html
  register: citrix_url

- name: download citrix
  become: yes
  get_url:
    url: "https:{{ citrix_url.stdout }}"
    dest: /tmp/ica.deb

- name: install citrix
  become: yes
  apt:
    deb: /tmp/ica.deb

- name: add SSL for citrix
  shell: "{{ item  }}"
  become: yes
  warn: no
  with_items:
    - rm -f /opt/Citrix/ICAClient/keystore/cacerts/*
    - ln -s /usr/share/ca-certificates/mozilla/* /opt/Citrix/ICAClient/keystore/cacerts/
    - c_rehash /opt/Citrix/ICAClient/keystore/cacerts/

- name: ensure plugin directories exist
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items:
    - /usr/lib/mozilla/plugins
    - /usr/lib/firefox-addons/plugins

- name: firefox - citrix plugin
  become: yes
  shell: "{{ item }}"
  warn: no
  with_items:
    - rm -f /usr/lib/firefox-addons/plugins/npica.so
    - rm -f /usr/lib/mozilla/plugins/npwrapper.npica.so /usr/lib/firefox/plugins/npwrapper.npica.so
    - rm -f /usr/lib/mozilla/plugins/npica.so
    - ln -s /opt/Citrix/ICAClient/npica.so /usr/lib/mozilla/plugins/npica.so
    - ln -s /opt/Citrix/ICAClient/npica.so /usr/lib/firefox-addons/plugins/npica.so

- name: chrome - citrix plugin
  shell: xdg-mime default wfica.desktop application/x-ica

