---
- name: proxy settings for bash.bashrc
  become: yes
  lineinfile:
    dest: /etc/bash.bashrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: 'return$'
  with_items:
   - { regexp: '^export http_proxy', line: "export http_proxy='{{ proxy_env.http_proxy }}'" }
   - { regexp: '^export https_proxy', line: "export https_proxy='{{ proxy_env.https_proxy }}'" }
   - { regexp: '^export HTTPS_PROXY', line: "export HTTPS_PROXY='{{ proxy_env.https_proxy }}'" }
   - { regexp: '^export ftp_proxy', line: "export ftp_proxy='{{ proxy_env.ftp_proxy }}'" }
   - { regexp: '^export no_proxy', line: "export no_proxy='{{ proxy_env.no_proxy }}'" }
       
- name: setting proxy for whole environment
  become: yes
  lineinfile:
    dest: /etc/environment
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: yes
  with_items:
    - { regexp: '^http_proxy', line: "http_proxy={{ proxy_env.http_proxy }}" }
    - { regexp: '^https_proxy', line: "https_proxy={{ proxy_env.https_proxy }}" }
    - { regexp: '^HTTPS_PROXY', line: "HTTPS_PROXY='{{ proxy_env.https_proxy }}'" }
    - { regexp: '^ftp_proxy', line: "ftp_proxy={{ proxy_env.ftp_proxy }}" }
    - { regexp: '^no_proxy', line: "no_proxy={{ proxy_env.no_proxy }}" }

- name: keep proxy settings when using sudo
  become: yes
  lineinfile:
      dest: /etc/sudoers
      regexp: "^Defaults\\s+env_keep"
      line: "Defaults\tenv_keep += \"http_proxy HTTPS_PROXY https_proxy ftp_proxy no_proxy DISPLAY XAUTHORITY\""
