---
- name: Install emacs
  become: yes
  apt:
    name: "{{ packages }}"
    state: latest
    install_recommends: no 
  vars:
    packages:
    - emacs-nox
    - git-el
    - python-mode
    - yaml-mode
    - elpa-lua-mode
