---
- name: Remove snap related packages
  become: yes
  apt:
    name: "{{ packages }}"
    state: absent
    purge: yes
    install_recommends: no 
  vars:
    packages:
    - snapd
    - snap
    - snap-confine
    - snapd-xdg-open
