---
- name: docker related services stop and manual start only
  become: yes
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - cadvisor
    - rawdns
    - containerd
    - runc
