- name: update apt packages
  become: yes
  apt:
    update_cache: yes

- name: install packages to allow apt to use repository offer HTTPS
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
