---
- name: Install wanted packages
  become: yes
  apt:
    name:
      - sshpass
      - htop
      - mc
      - openssh-server
      - f2fs-tools
      - deborphan
      - zile
      - putty
      - mtp-tools
      - jmtpfs
    state: latest
    update_cache: yes
    install_recommends: no   
...
