---
- name: journald Storage=none
  become: yes
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: 'Storage='
    line: Storage=none
    state: present

- name: restart journald
  become: yes
  command: systemctl restart systemd-journald
  
- name: delete /var/log/journal
  become: yes
  file:
    path: /var/log/journal/
    state: absent
