---
- name: Update repositories cache
  become: yes
  apt:
    update_cache: yes

- name: Console Editors
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    install_recommends: no 
  vars:
    packages:
    - ne
    - tilde
    - zile
    - vim
