---
- name: Update repositories cache
  become: yes
  apt:


- name: Console Editors
  become: yes
  apt:
    name:
      - ne
      - tilde
      - zile
      - vim
    state: latest
    update_cache: yes
    install_recommends: no 
